const fs = require('fs');
const path = require('path');

// Target path for the dynamically generated env-config.js
const outputPath = path.join(__dirname, '../js/env-config.js');

// Support multiple typical frontend environment variables
const apiUrl = process.env.VITE_API_URL || 
               process.env.REACT_APP_API_URL || 
               process.env.API_URL || 
               process.env.RENDER_API_URL || 
               '';

console.log(`[Build Script] Detected API URL: "${apiUrl || 'dynamic-fallback'}"`);

const fileContent = `/**
 * Dynamically generated configuration during build/deployment.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
window.ENV_CONFIG = {
  API_URL: ${JSON.stringify(apiUrl)}
};
`;

try {
  fs.writeFileSync(outputPath, fileContent, 'utf8');
  console.log(`[Build Script] Successfully generated ${outputPath}`);
} catch (error) {
  console.error('[Build Script] Failed to write config file:', error);
  process.exit(1);
}
